// Generated by https://quicktype.io

export interface Event {
  eventId:     number;
  userId:      number;
  eventName:   string;
  description: string;
  startDate:   string;
  endDate:     string;
  location:    string;
  apiEvents:   any[];
  eventlogs:   any[];
  user:        null;
}

